"""Generated by bh-bhengine-pyspark from a BH ENGINE pipeline.json.
Source pipeline: bh_oracle_s3
Secrets: set *_env variables from connections.yml before running.
JDBC/S3/Kafka jars: configured via spark.jars.packages (see main() builder).
Testable: call run_pipeline(spark, conns, fixtures={...}, sinks={}) with mock rows.

Layout: main.py (this file) + framework.py + glue.py.
Self-installing: `python main.py` installs requirements.txt on first run.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import glue  # noqa: F401 — cloud adapter beside framework.py
import framework as _bh_fw

# Stage bodies call _jdbc_* / _s3_* / _kafka_* helpers from framework.
globals().update(
    {k: v for k, v in vars(_bh_fw).items() if not k.startswith('__')}
)
_resolve_param_el = getattr(_bh_fw, '_resolve_param_el', lambda text, *args, **kwargs: text)


_ensure_dependencies()

from pyspark.sql import SparkSession  # noqa: E402
from pyspark.sql import functions as F  # noqa: E402
from pyspark.sql import Window  # noqa: E402

def run_pipeline(spark, conns, *, fixtures=None, sinks=None, params=None):
    """Run the migrated pipeline.

    fixtures: optional {reader_stage_name: [row_dict, ...]} to skip live I/O.
    sinks: optional dict; when provided, writers store DataFrames here instead of I/O.
    params: optional {KEY: value} pipeline parameter map (overrides parameters.yml).
    """
    fixtures = fixtures or {}
    params = params or {}

    if fixtures and "Oracle_JDBC_Table_1" in fixtures:
        Oracle_JDBC_Table_1 = spark.createDataFrame(fixtures["Oracle_JDBC_Table_1"])
    else:
        # Reader Oracle_JDBC_Table_1 (JDBC / Oracle)
        _conn = conns["migrate_jdbc"]
        _secrets = _fetch_secret(_conn)
        _require_secret_host(_conn, _secrets, kind="JDBC")
        _url = "jdbc:oracle:thin:@//{h}:{p}/{svc}".format(h=_secrets.get("host") or conns["migrate_jdbc"].get("host") or "", p=_secrets.get("port") or conns["migrate_jdbc"].get("port") or 1521, svc=_secrets.get("database") or _secrets.get("service_name") or conns["migrate_jdbc"].get("service_name") or conns["migrate_jdbc"].get("database") or "ORCL")
        _props = { "user": _secrets.get("username") or _secrets.get("user") or _env(_conn.get("username_env")) or _conn.get("username", "postgres"), "password": _secrets.get("password") or _secrets.get("pass") or _env(_conn.get("password_env")) or _conn.get("password", ""), "driver": _jdbc_driver(_conn.get("connection_type")), }
        _jdbc_table = _resolve_param_el("DBSFWUSER.${TABLE_NAME}", conns=conns, params=params)
        _num_partitions = 10
        _partition_col = _jdbc_discover_partition_column(spark, _url, _jdbc_table, _props)
        _lower_bound, _upper_bound = _jdbc_partition_bounds(spark, _url, _jdbc_table, _props, _partition_col)
        Oracle_JDBC_Table_1 = _jdbc_read_partitioned(
        spark, _url, _jdbc_table, _props,
        partition_column=_partition_col,
        lower_bound=_lower_bound,
        upper_bound=_upper_bound,
        num_partitions=_num_partitions,
    )
    Oracle_JDBC_Table_1 = _record_read("Oracle_JDBC_Table_1", Oracle_JDBC_Table_1)

    # SQL Spark_SQL_Query_1
    Oracle_JDBC_Table_1.createOrReplaceTempView("Oracle_JDBC_Table_1")
    Spark_SQL_Query_1 = spark.sql("select * FROM Oracle_JDBC_Table_1 where SERVICE_NAME <> 'MYSQL'")

    # Deduplicator Deduplicate_1
    Deduplicate_1 = Spark_SQL_Query_1.dropDuplicates()

    if sinks is not None:
        sinks["Amazon_S3_1"] = _sink_capture_df(Deduplicate_1)
    else:
        # Writer Amazon_S3_1 (S3 / csv)
        _conn = conns["migrate_s3"]
        _path = _s3_path(_conn, "", "bh-test/")
        _configure_s3(spark, _conn)
        (Deduplicate_1.write.mode("overwrite").option('header', True).option('sep', ",").option('quote', "\"").option('escape', "\\").csv(_path))
        _record_write(spark, "Amazon_S3_1", Deduplicate_1, _path, "csv", "overwrite")


def main():
    _configure_local_spark_env()
    # Prefer cwd (YARN --files / Glue extra files) then script dir.
    conns = _load_connections(_find_connections_file('connections.yml'))
    params = _resolve_submit_parameters(
        _load_parameters(_find_connections_file('parameters.yml'))
    )
    builder = SparkSession.builder.appName("bh_oracle_s3")
    _extra_jars = _spark_extra_jars(Path(__file__).parent)
    if _extra_jars:
        builder = builder.config('spark.jars', _extra_jars)
    # JVM jars for JDBC / s3a / Kafka (must be set before getOrCreate).
    # On managed AWS Spark, _spark_jar_packages drops hadoop-aws / AWS SDK.
    _jars = _spark_jar_packages("com.oracle.database.jdbc:ojdbc8:21.11.0.0,org.apache.hadoop:hadoop-aws:3.4.3,software.amazon.awssdk:bundle:2.35.4")
    if _jars:
        builder = builder.config('spark.jars.packages', _jars)
    spark = builder.getOrCreate()
    job = None
    try:
        from awsglue.context import GlueContext
        from awsglue.job import Job
        from awsglue.utils import getResolvedOptions
        try:
            args = getResolvedOptions(sys.argv, ['JOB_NAME'])
        except Exception:
            args = {'JOB_NAME': os.environ.get('JOB_NAME') or "bh_oracle_s3"}
        glue_context = GlueContext(spark.sparkContext)
        spark = glue_context.spark_session
        job = Job(glue_context)
        job.init(str(args.get('JOB_NAME') or ''), args)
    except ImportError:
        pass
    # Register JDBC drivers on the live JVM (no-op if --jars already loaded them).
    _ensure_jdbc_jars(spark)
    run_pipeline(spark, conns, params=params)
    ok = _pipeline_summary("bh_oracle_s3")
    if job is not None:
        job.commit()
    else:
        spark.stop()
    if not ok:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
