"""Generated by bh-bhengine-pyspark from a BH ENGINE pipeline.json.
Source pipeline: bh_posgres_s3_5_8
Secrets: set *_env variables from connections.yml before running.
JDBC/S3/Kafka jars: configured via spark.jars.packages (see main() builder).
Testable: call run_pipeline(spark, conns, fixtures={...}, sinks={}) with mock rows.

Layout: main.py (this file) + framework.py + glue.py.
Self-installing: `python main.py` installs requirements.txt on first run.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import glue  # noqa: F401 — cloud adapter beside framework.py
import framework as _bh_fw

# Stage bodies call _jdbc_* / _s3_* / _kafka_* helpers from framework.
globals().update(
    {k: v for k, v in vars(_bh_fw).items() if not k.startswith('__')}
)

_ensure_dependencies()

from pyspark.sql import SparkSession  # noqa: E402
from pyspark.sql import functions as F  # noqa: E402
from pyspark.sql import Window  # noqa: E402

def run_pipeline(spark, conns, *, fixtures=None, sinks=None, params=None):
    """Run the migrated pipeline.

    fixtures: optional {reader_stage_name: [row_dict, ...]} to skip live I/O.
    sinks: optional dict; when provided, writers store DataFrames here instead of I/O.
    params: optional {KEY: value} pipeline parameter map (overrides parameters.yml).
    """
    fixtures = fixtures or {}
    params = params or {}

    if fixtures and "PostgreSQL_JDBC_Table_1" in fixtures:
        PostgreSQL_JDBC_Table_1 = spark.createDataFrame(fixtures["PostgreSQL_JDBC_Table_1"])
    else:
        # Reader PostgreSQL_JDBC_Table_1 (JDBC / PostgreSQL)
        _conn = conns["migrate_postgres"]
        _secrets = _fetch_secret(_conn)
        _require_secret_host(_conn, _secrets, kind="JDBC")
        _url = "jdbc:postgresql://{h}:{p}/{db}".format(h=_secrets.get("host") or conns["migrate_postgres"].get("host") or "", p=_secrets.get("port") or conns["migrate_postgres"].get("port") or 5432, db=_secrets.get("database") or _secrets.get("dbname") or conns["migrate_postgres"].get("database") or "postgres")
        _props = { "user": _secrets.get("username") or _secrets.get("user") or _env(_conn.get("username_env")) or _conn.get("username", "postgres"), "password": _secrets.get("password") or _secrets.get("pass") or _env(_conn.get("password_env")) or _conn.get("password", ""), "driver": _jdbc_driver(_conn.get("connection_type")), }
        _jdbc_table = "public.sathish_test"
        _num_partitions = 10
        _partition_col = "ingest_date"
        _lower_bound, _upper_bound = _jdbc_partition_bounds(spark, _url, _jdbc_table, _props, _partition_col)
        PostgreSQL_JDBC_Table_1 = _jdbc_read_partitioned(
        spark, _url, _jdbc_table, _props,
        partition_column=_partition_col,
        lower_bound=_lower_bound,
        upper_bound=_upper_bound,
        num_partitions=_num_partitions,
    )
    PostgreSQL_JDBC_Table_1 = _record_read("PostgreSQL_JDBC_Table_1", PostgreSQL_JDBC_Table_1)

    # Expression Field_Renamer_1
    Field_Renamer_1 = PostgreSQL_JDBC_Table_1
    Field_Renamer_1 = _rename_column_ci(Field_Renamer_1, "id", "ID")
    Field_Renamer_1 = _rename_column_ci(Field_Renamer_1, "name", "NAME")
    Field_Renamer_1 = _rename_column_ci(Field_Renamer_1, "age", "AGE")
    Field_Renamer_1 = _rename_column_ci(Field_Renamer_1, "city", "CITY")
    Field_Renamer_1 = _rename_column_ci(Field_Renamer_1, "address", "ADDRESS")
    Field_Renamer_1 = _rename_column_ci(Field_Renamer_1, "state", "STATE")
    Field_Renamer_1 = _rename_column_ci(Field_Renamer_1, "zip", "ZIP")
    Field_Renamer_1 = _rename_column_ci(Field_Renamer_1, "time", "TIME")
    Field_Renamer_1 = _rename_column_ci(Field_Renamer_1, "phone", "PHONE")

    # Expression Field_Remover_1
    Field_Remover_1 = Field_Renamer_1
    Field_Remover_1 = Field_Remover_1.drop("ingest_timestamp")

    if sinks is not None:
        sinks["Amazon_S3_1"] = _sink_capture_df(Field_Remover_1)
    else:
        # Writer Amazon_S3_1 (S3 / parquet)
        _conn = conns["migrate_s3"]
        _path = _s3_path(_conn, "${B}", "")
        _configure_s3(spark, _conn)
        (Field_Remover_1.write.mode("append").parquet(_path))
        _record_write(spark, "Amazon_S3_1", Field_Remover_1, _path, "parquet", "append")


def main():
    _configure_local_spark_env()
    # Prefer cwd (YARN --files / Glue extra files) then script dir.
    conns = _load_connections(_find_connections_file('connections.yml'))
    params = _resolve_submit_parameters(
        _load_parameters(_find_connections_file('parameters.yml'))
    )
    spark = None
    job = None
    try:
        from awsglue.context import GlueContext
        from awsglue.job import Job
        from awsglue.utils import getResolvedOptions
        from pyspark.context import SparkContext
        try:
            args = getResolvedOptions(sys.argv, ['JOB_NAME'])
        except Exception:
            args = {'JOB_NAME': os.environ.get('JOB_NAME') or "bh_posgres_s3_5_8"}
        sc = SparkContext.getOrCreate()
        glue_context = GlueContext(sc)
        spark = glue_context.spark_session
        job = Job(glue_context)
        job.init(str(args.get('JOB_NAME') or ''), args)
    except ImportError:
        builder = SparkSession.builder.appName("bh_posgres_s3_5_8")
        _extra_jars = _spark_extra_jars(Path(__file__).parent)
        if _extra_jars:
            builder = builder.config('spark.jars', _extra_jars)
        # JVM jars for JDBC / s3a / Kafka (must be set before getOrCreate).
        # On managed AWS Spark, _spark_jar_packages drops hadoop-aws / AWS SDK.
        _jars = _spark_jar_packages("org.postgresql:postgresql:42.7.12,org.apache.hadoop:hadoop-aws:3.4.3,software.amazon.awssdk:bundle:2.35.4")
        if _jars:
            builder = builder.config('spark.jars.packages', _jars)
        spark = builder.getOrCreate()
    # Register JDBC drivers on the live JVM (no-op if --jars already loaded them).
    _ensure_jdbc_jars(spark)
    run_pipeline(spark, conns, params=params)
    ok = _pipeline_summary("bh_posgres_s3_5_8")
    if job is not None:
        job.commit()
    else:
        spark.stop()
    if not ok:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
