"""Generated by bh-bhengine-pyspark from a BH ENGINE pipeline.json.
Source pipeline: bh_kafka_s3_5_8
Secrets: set *_env variables from connections.yml before running.
JDBC/S3/Kafka jars: configured via spark.jars.packages (see main() builder).
Testable: call run_pipeline(spark, conns, fixtures={...}, sinks={}) with mock rows.

Layout: main.py (this file) + framework.py + glue.py.
Self-installing: `python main.py` installs requirements.txt on first run.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import glue  # noqa: F401 — cloud adapter beside framework.py
import framework as _bh_fw

# Stage bodies call _jdbc_* / _s3_* / _kafka_* helpers from framework.
globals().update(
    {k: v for k, v in vars(_bh_fw).items() if not k.startswith('__')}
)

_ensure_dependencies()

from pyspark.sql import SparkSession  # noqa: E402
from pyspark.sql import functions as F  # noqa: E402
from pyspark.sql import Window  # noqa: E402

def run_pipeline(spark, conns, *, fixtures=None, sinks=None, params=None):
    """Run the migrated pipeline.

    fixtures: optional {reader_stage_name: [row_dict, ...]} to skip live I/O.
    sinks: optional dict; when provided, writers store DataFrames here instead of I/O.
    params: optional {KEY: value} pipeline parameter map (overrides parameters.yml).
    """
    fixtures = fixtures or {}
    params = params or {}

    _sr_decoded = False
    if fixtures and "Kafka_1" in fixtures:
        Kafka_1 = spark.createDataFrame(fixtures["Kafka_1"])
    else:
        # Reader Kafka_1 (Kafka batch)
        _conn = conns["migrate_kafka"]
        _secrets = _fetch_secret(_conn)
        _bootstrap = _secrets.get('bootstrap_servers') or _conn.get('bootstrap_servers') or ''
        _subscribe = (_secrets.get('subscribe') or _conn.get('subscribe') or _secrets.get('topic') or _conn.get('topic') or "test-prem-01")
        _kr = (
        spark.read.format('kafka')
        .option('kafka.bootstrap.servers', _bootstrap)
        .option('subscribe', _subscribe)
        .option('startingOffsets', 'earliest')
    )
        _secrets = _fetch_secret(_conn)
        _sec = str(_secrets.get('security_protocol') or _conn.get('security_protocol') or '').strip().upper()
        if _sec and _sec != 'PLAINTEXT':
            _kr = _kr.option('kafka.security.protocol', _sec)
        _ca_pem = _secrets.get('ssl_ca_pem') or _conn.get('ssl_ca_pem')
        if not _ca_pem and _sec in ('SSL', 'SASL_SSL') and not os.path.exists(str(_secrets.get('ssl_truststore_location') or _conn.get('ssl_truststore_location') or '')):
            try:
                import ssl
                _srv = str(_secrets.get('bootstrap_servers') or _conn.get('bootstrap_servers') or '').split(',')[0].strip()
                if ':' in _srv:
                    _h, _p = _srv.split(':', 1)
                    _ca_pem = ssl.get_server_certificate((_h, int(_p)))
            except Exception:
                pass
        if _ca_pem:
            _ca_path = _kafka_pem_path(spark, _ca_pem, name='kafka_ca.pem')
            _kr = _kr.option('kafka.ssl.truststore.location', _ca_path)
            _kr = _kr.option('kafka.ssl.truststore.type', 'PEM')
        else:
            _ts_loc = _secrets.get('ssl_truststore_location') or _conn.get('ssl_truststore_location')
            if _ts_loc and os.path.exists(str(_ts_loc)):
                _ts_path = _kafka_ssl_ship_file(spark, _ts_loc)
                _kr = _kr.option('kafka.ssl.truststore.location', _ts_path)
                if str(_ts_loc).lower().endswith(('.p12', '.pfx')):
                    _kr = _kr.option('kafka.ssl.truststore.type', 'PKCS12')
                elif str(_ts_loc).lower().endswith('.jks'):
                    _kr = _kr.option('kafka.ssl.truststore.type', 'JKS')
                elif str(_ts_loc).lower().endswith(('.pem', '.crt')):
                    _kr = _kr.option('kafka.ssl.truststore.type', 'PEM')
                _ts_pass = (_env(_conn.get('ssl_truststore_password_env')) or _secrets.get('ssl_truststore_password') or _conn.get('ssl_truststore_password') or _secrets.get('truststorePassword') or _secrets.get('truststore_password'))
                if _ts_pass:
                    _kr = _kr.option('kafka.ssl.truststore.password', _ts_pass)
        _cert_pem = _secrets.get('ssl_cert_pem') or _conn.get('ssl_cert_pem')
        _key_pem = _secrets.get('ssl_key_pem') or _conn.get('ssl_key_pem')
        if _cert_pem and _key_pem:
            _ks_path = _kafka_pem_path(
                spark,
                str(_cert_pem).strip() + '\n' + str(_key_pem).strip(),
                name='kafka_ks.pem',
            )
            _kr = _kr.option('kafka.ssl.keystore.location', _ks_path)
            _kr = _kr.option('kafka.ssl.keystore.type', 'PEM')
            _key_pass = (_env(_conn.get('ssl_key_password_env')) or _secrets.get('ssl_key_password') or _conn.get('ssl_key_password'))
            if _key_pass and _pem_private_key_is_encrypted(_key_pem):
                _kr = _kr.option('kafka.ssl.key.password', _key_pass)
        else:
            _ks_loc = _secrets.get('ssl_keystore_location') or _conn.get('ssl_keystore_location')
            _ks_pass = (_env(_conn.get('ssl_keystore_password_env')) or _secrets.get('ssl_keystore_password') or _conn.get('ssl_keystore_password') or _secrets.get('keystorePassword') or _secrets.get('keystore_password') or _secrets.get('ssl_key_password') or _secrets.get('keyPassword'))
            if _ks_loc and os.path.exists(str(_ks_loc)) and _ks_pass:
                _ks_path = _kafka_ssl_ship_file(spark, _ks_loc)
                _kr = _kr.option('kafka.ssl.keystore.location', _ks_path)
                if str(_ks_loc).lower().endswith(('.p12', '.pfx')):
                    _kr = _kr.option('kafka.ssl.keystore.type', 'PKCS12')
                _kr = _kr.option('kafka.ssl.keystore.password', _ks_pass)
                _key_pass = (_env(_conn.get('ssl_key_password_env')) or _secrets.get('ssl_key_password') or _conn.get('ssl_key_password') or _secrets.get('keyPassword'))
                if _key_pass:
                    _kr = _kr.option('kafka.ssl.key.password', _key_pass)
        _sasl_user = _env(_conn.get('sasl_username_env')) or _secrets.get('sasl_username') or _conn.get('sasl_username') or _secrets.get('username')
        _sasl_pass = _env(_conn.get('sasl_password_env')) or _secrets.get('sasl_password') or _conn.get('sasl_password') or _secrets.get('password')
        if _sasl_user:
            _kr = _kr.option(
                "kafka.security.protocol", _secrets.get("security_protocol") or _conn.get("security_protocol") or "SASL_SSL")
            _kr = _kr.option(
                "kafka.sasl.mechanism", _secrets.get("sasl_mechanism") or _conn.get("sasl_mechanism") or "PLAIN")
            _jaas = ('org.apache.kafka.common.security.plain.PlainLoginModule required '
         'username="' + str(_sasl_user).replace('\\', '\\\\').replace('"', '\\"') + '" '
         'password="' + str(_sasl_pass or '').replace('\\', '\\\\').replace('"', '\\"') + '";')
            _kr = _kr.option("kafka.sasl.jaas.config", _jaas)
        Kafka_1 = _kr.load()
        _sr_url = _secrets.get('schema_registry_url') or _conn.get('schema_registry_url')
        if _sr_url:
            try:
                import urllib.request
                from urllib.parse import quote
                _sr_headers = {'Accept': 'application/vnd.schemaregistry.v1+json, application/json'}
                _sr_client_id = _secrets.get('schema_registry_client_id') or _conn.get('schema_registry_client_id')
                if _sr_client_id:
                    _t_id = _secrets.get('schema_registry_tenant_id') or _conn.get('schema_registry_tenant_id')
                    _c_sec = _secrets.get('schema_registry_client_secret') or _conn.get('schema_registry_client_secret')
                    _scope = _secrets.get('schema_registry_scope') or f'{_sr_client_id}/.default'
                    _t_req = urllib.request.Request(
                        f'https://login.microsoftonline.com/{_t_id}/oauth2/v2.0/token',
                        data=f'grant_type=client_credentials&client_id={_sr_client_id}&client_secret={quote(_c_sec or "")}&scope={quote(_scope or "")}'.encode('utf-8'),
                        headers={'Content-Type': 'application/x-www-form-urlencoded'}
                    )
                    with urllib.request.urlopen(_t_req) as _t_resp:
                        _tok = json.loads(_t_resp.read().decode('utf-8')).get('access_token')
                        if _tok:
                            _sr_headers['Authorization'] = f'Bearer {_tok}'
                _sr_req = urllib.request.Request(f'{_sr_url.rstrip("/")}/subjects/{quote(str(_subscribe))}-value/versions/latest', headers=_sr_headers)
                with urllib.request.urlopen(_sr_req) as _sr_resp:
                    _schema_json = json.loads(_sr_resp.read().decode('utf-8')).get('schema')
                    if _schema_json:
                        _json_lines = Kafka_1.select(F.col('value').cast('string').alias('_json'))
                        Kafka_1 = spark.read.json(_json_lines.rdd.map(lambda row: row['_json']))
                        _sr_decoded = True
            except Exception:
                pass
    if not _sr_decoded and 'value' in Kafka_1.columns:
        _json_lines = Kafka_1.select(F.col('value').cast('string').alias('_json'))
        Kafka_1 = spark.read.json(_json_lines.rdd.map(lambda row: row['_json']))
    Kafka_1 = _record_read("Kafka_1", Kafka_1)

    if sinks is not None:
        sinks["Amazon_S3_1"] = _sink_capture_df(Kafka_1)
    else:
        # Writer Amazon_S3_1 (S3 / json)
        _conn = conns["migrate_s3"]
        _path = _s3_path(_conn, "", "bh-kafka/")
        _configure_s3(spark, _conn)
        (Kafka_1.write.mode("append").json(_path))
        _record_write(spark, "Amazon_S3_1", Kafka_1, _path, "json", "append")


def main():
    _configure_local_spark_env()
    # Prefer cwd (YARN --files / Glue extra files) then script dir.
    conns = _load_connections(_find_connections_file('connections.yml'))
    params = _resolve_submit_parameters(
        _load_parameters(_find_connections_file('parameters.yml'))
    )
    builder = SparkSession.builder.appName("bh_kafka_s3_5_8")
    _extra_jars = _spark_extra_jars(Path(__file__).parent)
    if _extra_jars:
        builder = builder.config('spark.jars', _extra_jars)
    # JVM jars for JDBC / s3a / Kafka (must be set before getOrCreate).
    # On managed AWS Spark, _spark_jar_packages drops hadoop-aws / AWS SDK.
    _jars = _spark_jar_packages("org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.apache.spark:spark-token-provider-kafka-0-10_2.12:3.5.1,org.apache.kafka:kafka-clients:3.4.1,org.apache.commons:commons-pool2:2.11.1,org.apache.hadoop:hadoop-aws:3.4.3,software.amazon.awssdk:bundle:2.35.4")
    if _jars:
        builder = builder.config('spark.jars.packages', _jars)
    spark = builder.getOrCreate()
    job = None
    try:
        from awsglue.context import GlueContext
        from awsglue.job import Job
        from awsglue.utils import getResolvedOptions
        try:
            args = getResolvedOptions(sys.argv, ['JOB_NAME'])
        except Exception:
            args = {'JOB_NAME': os.environ.get('JOB_NAME') or "bh_kafka_s3_5_8"}
        glue_context = GlueContext(spark.sparkContext)
        spark = glue_context.spark_session
        job = Job(glue_context)
        job.init(str(args.get('JOB_NAME') or ''), args)
    except ImportError:
        pass
    run_pipeline(spark, conns, params=params)
    ok = _pipeline_summary("bh_kafka_s3_5_8")
    if job is not None:
        job.commit()
    else:
        spark.stop()
    if not ok:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
